### ISSUE TITLE
Rankup prefix error

### ISSUE THREAD

**Issue by RedPandaTGP** [devhid/PEX-Rankup#2]
When my players type /rankup they rankup if they have the proper amount of money but their prefix does not change from the previous rank they were. If they were rank C and ranked up to B their prefix stays at the C rank prefix. I'm not sure how to fix the problem. Thank you for your time :+1:

**Comment by devhid** [comment]
Hello,

Could you show me your config.yml for PEX-Rankup and your permissions.yml for PermissionsEx?

Also, why are you ranking up in reverse? (From Rank C to Rank B)

Thanks, Hid

**Comment by RedPandaTGP** [comment]
On my server the ranks go C,B,A,Elite,Free so the rank system does go reversed but that part is correct. Here is my config.yml for PermissionsEx-Rankup and permissions.yml for PermissionsEx>

[BothFiles.zip](https://github.com/devhid/PEX-Rankup/files/365245/BothFiles.zip)

**Comment by devhid** [comment]
I think my plugin may be case sensitive. Change the "C-rank" in the PEX-Rankup config.yml to "C-Rank". That may solve the issue.

Also, can you check if the user's rank actually changes when they type of /rankup? What I mean by that: when someone is C-Rank, and they type in /rankup, does /pex user <user who ranked up> show that their group is B-Rank? Or does the group stay at C-Rank? (I'm not talking about the prefix, but the actual group they are in).

Thanks, Hid

**Comment by RedPandaTGP** [comment]
When a player does /rankup it announces that they have ranked up to the next rank, but if they chat their prefix doesn't change and niether does their permissions or group. I also typed the ranks exactly as i created them to make sure there were no case sensitivity problems, though it did not seem to change it.

**Comment by devhid** [comment]
Any errors or messages in console when that happens?

Anything like "Could not find next rank for <player>." etc..?

**Comment by RedPandaTGP** [comment]
No, there's no error messages in console

**Comment by devhid** [comment]
Hmm, this is very odd.

Sorry for asking so many questions, I'm trying to narrow down the issue:

What version of Spigot are you running?

What version of PermissionsEx are you running?

Do you have Vault and Essentials (or any plugin that handles economy) installed?

Thanks, Hid.

**Comment by RedPandaTGP** [comment]
I have both Essentials and Vault installed, also PermissionsEx is on version 1.23.4 and Spigot for 1.9

**Comment by RedPandaTGP** [comment]
wtf

**Comment by devhid** [comment]
I never tested my plugin on 1.9. I will try to replicate your problem and setup to find the issue. 

If I could ask for one last thing, what plugins do you currently have installed? There might be a plugin conflict.

Thanks, Hid.

**Comment by RedPandaTGP** [comment]
Well i have a lot of plugins, about 50 of them so would you like a whole list of all of them?

**Comment by devhid** [comment]
If you could that would be much appreciated.

**Comment by devhid** [comment]
I tried to replicate your problem using your PEX-Rankup config.yml and your permissions.yml on a Spigot 1.9.4 server. There was a problem with group registration by PEX so I played around with the permissions.yml a bit and I got it to work.

Try this permissions.yml configuration: http://hastebin.com/qomecirule.sm

If you type in /rankup and you check their group using /pex user <name> and you see that the group changed (from C-Rank to B-Rank for example), then the problem is fixed.

 If there's any problems with prefixes not showing up or anything like that, that's most likely a problem on your end with either incorrect EssentialsChat setup or something with your permissions.yml (if you edit it in the future).

Please tell me if it works.

Thanks, Hid.
