### ISSUE TITLE
[FEATURE] Few suggestions for pex-rankup ;)

### ISSUE THREAD

**Issue by maxlehot1234** [devhid/PEX-Rankup#5]
Hi, I have few suggestions for you:

1- Add a rankup price reducer base on the player permission.
EX: If the player have: pexrankup.multiplier.15 --> 15% off for rankups

2- Add an option to add colored prefix inside pex-rankup config

3- Maybe action when player rankup

4- Send actionbar, bossbar, title when player rankup

5- Particles when player rankup

6- Add a progress bar or a percentage to reach the next rankup

I think it's good for the moment, but it will be a really big UPDATE ;)

**Comment by maxlehot1234** [comment]
@devhid It's funny. We create issue, but no answer

**Comment by devhid** [comment]
Remember, I work on this plugin in my free time with no compensation. I could abandon this plugin right now if I wanted to, but I won't. I haven't forgotten about anything. It's the beginning of the weekend and my homework takes priority.

**Comment by maxlehot1234** [comment]
Ok, it is just to know if you are alive ;)

**Comment by devhid** [comment]
1) Nope.
2) You can already have a colored prefix. Just edit the configuration file.
3) You can already perform actions when a player ranks up. Look at "execute-commands-upon-rankup" in the configuration file.
4) Nope.
5) Nope.
6) Nope.

The reason for the "nopes" is because I'm not trying to replace EZRanksLite or Pro. I don't want to be a replica and add big features like those. I just want a simple, lightweight, alternate solution for people who do not want the feature-packed rankup plugin extended_clip offers.

**Comment by maxlehot1234** [comment]
I understand. But the rankup event allow my dev to create something like this to replace your nopes?

**Comment by devhid** [comment]
Yes.
