### ISSUE TITLE
Remove rankup message

### ISSUE THREAD

**Issue by maxlehot1234** [devhid/PEX-Rankup#6]
Is it possible to remove the rankup message ?

Add actions per rankup to make your plugin more configurable.

Thanks

**Comment by devhid** [comment]
If you're talking about the rankup-broadcast, then sure I'll add an option to disable the broadcast.

Regarding the actions per rankup feature, that would highly over complicate the plugin. I would like to keep this lightweight as possible. But, I'll add a RankupEvent so that your developer can use my plugin and create a custom plugin for you so that when a player ranks up, the RankupEvent is fired and you can check the rank and do whatever you need to do.

**Comment by maxlehot1234** [comment]
@devhid Ok thank you so much and the rankupevent would be a really nice idea ;) Thanks
